version: '3.9'
services:

  client-app:
    build: ./client
    container_name: client_headless
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    image: mysql
    container_name: db-headless
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wp-headless
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX}
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    container_name: pma-headless
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: '1'

volumes:
  wordpress:
  database:

